#!/usr/bin/python3
def raise_exception():
    name = "Davud"
    name / 5
